# Week 1 Python and Data Engineering Assessment

## Task 3: NumPy, Pandas and Matplotlib

### Employee Data Analysis

This notebook contains employee data analysis, data cleaning, statistical summaries and visualizations.

In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


employees = pd.read_csv("../data/employees.csv")

print("EMPLOYEE DATA")
display(employees)


print("\nDATASET INFORMATION")
employees.info()

print("\nSTATISTICAL SUMMARY")
display(employees.describe())


print("\nTOTAL EMPLOYEES:", len(employees))

print("\nHEADCOUNT BY DEPARTMENT")
print(employees["department"].value_counts())

EMPLOYEE DATA

   id     name department  salary       city
0   1     Arun      Sales   30000    Chennai
1   2    Priya         HR   45000    Chennai
2   3    Rahul         IT   60000  Bangalore
3   4    Divya         IT   75000    Chennai
4   5  Karthik    Finance   90000     Mumbai
5   6    Meena      Sales   52000  Bangalore
6   7   Suresh         IT   68000    Chennai
7   8   Anitha         HR   48000     Mumbai

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          8 non-null      int64
 1   name        8 non-null      str
 2   department  8 non-null      str
 3   salary      8 non-null      int64
 4   city        8 non-null      str
dtypes: int64(2), str(3)
memory usage: 452.0 bytes

STATISTICAL SUMMARY

            id        salary
count  8.00000      8.000000
mean   4.50000  58500.000000
std    2.44949  18913.336187
min    1.00000  30000.000000
25%    2.75000  47250.000000
50%    4.50000  56000.000000
75%    6.25000  69750.000000
max    8.00000  90000.000000

TOTAL EMPLOYEES: 8

HEADCOUNT BY DEPARTMENT
department
IT         3
Sales      2
HR         2
Finance    1
Name: count, dtype: int64

In [3]:
employees_dirty = employees.copy()

employees_dirty.loc[1, "salary"] = None
employees_dirty.loc[4, "salary"] = None

employees_dirty = pd.concat(
    [employees_dirty, employees_dirty.iloc[[0]]],
    ignore_index=True
)

median_salary = employees_dirty["salary"].median()

employees_dirty["salary"] = employees_dirty["salary"].fillna(median_salary)

employees_dirty = employees_dirty.drop_duplicates()

employees_dirty["salary"] = employees_dirty["salary"].astype(int)

display(employees_dirty)

   id     name department  salary       city
0   1     Arun      Sales   30000    Chennai
1   2    Priya         HR   52000    Chennai
2   3    Rahul         IT   60000  Bangalore
3   4    Divya         IT   75000    Chennai
4   5  Karthik    Finance   52000     Mumbai
5   6    Meena      Sales   52000  Bangalore
6   7   Suresh         IT   68000    Chennai
7   8   Anitha         HR   48000     Mumbai

In [4]:
department_summary = employees_dirty.groupby("department").agg(
    headcount=("id", "count"),
    average_salary=("salary", "mean"),
    maximum_salary=("salary", "max")
)

display(department_summary)

            headcount  average_salary  maximum_salary
department
Finance             1    52000.000000           52000
HR                  2    50000.000000           52000
IT                  3    67666.666667           75000
Sales               2    41000.000000           52000

In [5]:
departments = pd.read_csv("../Task3/departments.csv")

inner_join = pd.merge(
    employees_dirty,
    departments,
    on="department",
    how="inner"
)

display(inner_join)

   id     name department  salary       city     head  budget
0   1     Arun      Sales   30000    Chennai     Arun  500000
1   2    Priya         HR   52000    Chennai    Priya  300000
2   3    Rahul         IT   60000  Bangalore    Rahul  800000
3   4    Divya         IT   75000    Chennai    Rahul  800000
4   5  Karthik    Finance   52000     Mumbai  Karthik  400000
5   6    Meena      Sales   52000  Bangalore     Arun  500000
6   7   Suresh         IT   68000    Chennai    Rahul  800000
7   8   Anitha         HR   48000     Mumbai    Priya  300000

In [6]:
left_join = pd.merge(
    employees_dirty,
    departments,
    on="department",
    how="left"
)

display(left_join)

   id     name department  salary       city     head  budget
0   1     Arun      Sales   30000    Chennai     Arun  500000
1   2    Priya         HR   52000    Chennai    Priya  300000
2   3    Rahul         IT   60000  Bangalore    Rahul  800000
3   4    Divya         IT   75000    Chennai    Rahul  800000
4   5  Karthik    Finance   52000     Mumbai  Karthik  400000
5   6    Meena      Sales   52000  Bangalore     Arun  500000
6   7   Suresh         IT   68000    Chennai    Rahul  800000
7   8   Anitha         HR   48000     Mumbai    Priya  300000

In [7]:
outer_join = pd.merge(
    employees_dirty,
    departments,
    on="department",
    how="outer"
)

display(outer_join)

    id     name department   salary       city     head  budget
0  5.0  Karthik    Finance  52000.0     Mumbai  Karthik  400000
1  2.0    Priya         HR  52000.0    Chennai    Priya  300000
2  8.0   Anitha         HR  48000.0     Mumbai    Priya  300000
3  3.0    Rahul         IT  60000.0  Bangalore    Rahul  800000
4  4.0    Divya         IT  75000.0    Chennai    Rahul  800000
5  7.0   Suresh         IT  68000.0    Chennai    Rahul  800000
6  NaN      NaN  Marketing      NaN        NaN    Meena  250000
7  1.0     Arun      Sales  30000.0    Chennai     Arun  500000
8  6.0    Meena      Sales  52000.0  Bangalore     Arun  500000

In [8]:
%timeit employees["salary"].mean()

38.5 μs ± 4.85 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)